let products = 
[
	{
		id: "00000001",
       	name: "Big Bennie's Broccoli",
        image: "https://images-na.ssl-images-amazon.com/images/I/71mYzDfK-6L._SL1024_.jpg",
        price: 4.99,
        rating: 2.5,
        description: "Rich green broccoli",
        category: "produce",
    },
    {
    	id: "00000002",
        name: "Fryer Whole Chicken",
        image: "https://images-na.ssl-images-amazon.com/images/I/612jiEdQ58L._SL1000_.jpg",
        price: 9.99,
        rating: 3.5,
        description: "Juicy chicken",
        category: "Meat",
    },
    {
        id: "00000003",
        name: "Orange",
        image: "https://images-na.ssl-images-amazon.com/images/I/31mXuKEEV9L.jpg",
        price: 2.49,
        rating: 4.7,
        description: "Juicy Orange",
    },
    {
        id: "00000004",
        name: "Avocado Hass Organic",
        image: "https://images-na.ssl-images-amazon.com/images/I/71f1v-UDYNL._SL1500_.jpg",
        price: 1.59,
        rating: 4.1,
        description: "Large Avocado",
        category: "Vegetables",
    },
    {
        id: "00000005",
        name: "Yellow Apple",
        image: "https://images-na.ssl-images-amazon.com/images/I/51HJMkwj3LL._SL1024_.jpg",
        price: 9.99,
        rating: 4.8,
        description: "Organic Apple",
        category: "Fruit",
    },
    {    
        id: "00000006",
        name: "Chobani Non-Fat Greek Yogurt",
        image: "https://images-na.ssl-images-amazon.com/images/I/61BfwH%2BEVbL._SL1313_.jpg",
        price: 1.25,
        rating: 3.8,
        description: "Plain 5.3oz",
        category: "Dairy",
    },
    {
        id: "00000007",
        name: "Mini Cucumber",
        image: "https://images-na.ssl-images-amazon.com/images/I/81ED72E4niL._SL1500_.jpg",
        price: 3.55,
        rating: 3.2,
        description: "12 Ounce",
        category: "Vegetables",
    },
    {
        id: "00000008",
        name: "Bob's Quick Oats",
        image: "https://images-na.ssl-images-amazon.com/images/I/61OAwLaMhPL._SL1000_.jpg",
        price: 8.79,
        rating: 4.7,
        description: "Gluten Free",
        category: "Canned & Packaged",
    },
    {
        id: "00000009",
        name: "Berry Blueberry",
        image: "https://images-na.ssl-images-amazon.com/images/I/71%2Bq3L500EL._SL1500_.jpg",
        price: 6.99,
        rating: 5.0,
        description: "Organic",
        category: "Fruit",
    },
    {
        id: "00000010",
        name: "Berry Raspberry",
        image: "https://images-na.ssl-images-amazon.com/images/I/7166lg-faIL._SL1500_.jpg",
        price: 5.99,
        rating: 4.3,
        description: "Organic- 6 Ounce",
        category: "Fruit",
    },
    {
        id: "00000011",
        name: "Baby Spinach",
        image: "https://images-na.ssl-images-amazon.com/images/I/81uy4iuhG9L._SL1500_.jpg",
        price: 3.05,
        rating: 4.3,
        description: "Triple Washed",
        category: "Vegetables",
    },
    {
        id: "00000012",
        name: "Berry Stawberries",
        image: "https://images-na.ssl-images-amazon.com/images/I/818T0jU5rLL._SL1500_.jpg",
        price: 4.99,
        rating: 2.5,
        description: "Organic",
        category: "Fruit",
    },
    {
        id: "00000013",
        name: "Scallions Green Onion",
        image: "https://images-na.ssl-images-amazon.com/images/I/711gm2pLXdL._SL1500_.jpg",
        price: 1.67,
        rating: 2.3,
        description: "Organic",
        category: "Vegetables",
    },
    {
        id: "00000014",
        name: "Atlantic Salmon Fillet",
        image: "https://images-na.ssl-images-amazon.com/images/I/51l3V5KgNWL._SL1000_.jpg",
        price: 17.89,
        rating: 4.6,
        description: "wild-caught",
        category: "Meat & Seafood",
    },
    {
        id: "00000015",
        name: "Hot Cocoa",
        image: "https://images-na.ssl-images-amazon.com/images/I/91-hQYuoE%2BL._SL1500_.jpg",
        price: 9.57,
        rating: 2.8,
        description: "10 pack",
        category: "Dairy",
    },
    {
        id: "00000016",
        name: "Bell Pepper",
        image: "https://images-na.ssl-images-amazon.com/images/I/71bL2SGtC0L._SL1500_.jpg",
        price: 1.99,
        rating: 4.9,
        description: "Green",
        category: "Vegetables",
    },
    {
        id: "00000017",
        name: "Fresh Onion",
        image: "https://images-na.ssl-images-amazon.com/images/I/71kZWXeA04L._SL1500_.jpg",
        price: 2.23,
        rating: 3.6,
        description: "Yellow",
        category: "Vegetables",
    },
    {
        id: "00000018",
        name: "Organic Carrot",
        image: "https://images-na.ssl-images-amazon.com/images/I/81orPM4jMWL._SL1500_.jpg",
        price: 2.78,
        rating: 4.5,
        description: "0.5lb",
        category: "Vegetables"
    },
    {
        id: "00000019",
        name: "Lemon Reg Conventional",
        image: "https://images-na.ssl-images-amazon.com/images/I/710O%2BMVcd6L._SL1500_.jpg",
        price: 0.99,
        rating: 3.0,
        description: "Freshness Guarantee",
        category: "Vegetables",
    },
    {
        id: "00000020",
        name: "Organic Fuji Apple",
        image: "https://images-na.ssl-images-amazon.com/images/I/71nYAofeGAL._SL1433_.jpg",
        price: 4.12,
        rating: 5.0,
        description: "Organic",
        category: "Fruit",
    },
    {
        id: "00000021",
        name: "Jalapeno Peppber",
        image: "https://images-na.ssl-images-amazon.com/images/I/612H5Z1GWEL._SL1500_.jpg",
        price: 1.49,
        rating: 4.5,
        description: "Green",
        category: "Vegetables",
    },
    {
        id: "00000022",
        name: "MEAT Ground Beaf",
        image: "https://images-na.ssl-images-amazon.com/images/I/81AZdusR0VL._SL1500_.jpg",
        price: 8.99,
        rating: 4.7,
        description: "90% Lean/ 10% Fat",
        category: "Meat & Seafood",
    },
    {
        id: "00000023",
        name: "MEAT Boneless Beef",
        image: "https://images-na.ssl-images-amazon.com/images/I/51hkEEzdqaL._SL1000_.jpg",
        price: 16.99,
        rating: 4.8,
        description: "New York Strip Steak",
        category: "Meat & Seafood",
    },
    {
        id: "00000024",
        name: "Banana",
        image: "https://images-na.ssl-images-amazon.com/images/I/3144ORokt4L.jpg",
        price: 0.48,
        rating: 4.3,
        description: "Organic",
        category: "Fruit",
    },
    {
        id: "00000025",
        name: "Lime Regular Conventional",
        image: "https://images-na.ssl-images-amazon.com/images/I/81OLG79WS%2BL._SL1500_.jpg",
        price: 0.39,
        rating: 2.2,
        description: "Fresh",
        category: "Vegetables",
    },
    {
        id: "00000026",
        name: "Poche's Pork Sausage",
        image: "https://images-na.ssl-images-amazon.com/images/I/41F43AeBQBL.jpg",
        price: 7.99,
        rating: 3.4,
        description: "Fresh",
        category: "Meat & Seafood",
    },
    {
        id: "00000027",
        name: "Medium Hass Avocado",
        image: "https://images-na.ssl-images-amazon.com/images/I/714d4oRD6YL._SL1500_.jpg",
        price: 1.39,
        rating: 4.4,
        description: "Fresh",
        category: "Vegetables",
    },
    {
        id: "00000028",
        name: "Grade A Milk",
        image: "https://images-na.ssl-images-amazon.com/images/I/71pokGgV2XL._SL1500_.jpg",
        price: 9.99,
        rating: 3.5,
        description: "Organic",
        category: "Dairy",
    },
    {
        id: "00000029",
        name: "Organic Almond Milk",
        image: "https://images-na.ssl-images-amazon.com/images/I/61Zyz33L5bL._SL1000_.jpg",
        price: 4.49,
        rating: 4.8,
        description: "Unsweetened",
        category: "Dairy",
    },
    {
        id: "00000030",
        name: "Spring Water",
        image: "https://images-na.ssl-images-amazon.com/images/I/615ulNxnihL._SL1000_.jpg",
        price: 2.67,
        rating: 5.0,
        description: "1 Gallon",
        category: "Drinks",
    },
    {
        id: "00000031",
        name: "Simply Orange",
        image: "https://images-na.ssl-images-amazon.com/images/I/81eqC%2B9aewL._SL1500_.jpg",
        price: 4.39,
        rating: 3.5,
        description: "100% Juice Not from Concentrate",
        category: "Drinks",
    },
    {
        id: "00000032",
        name: "Honest Tea",
        image: "https://images-na.ssl-images-amazon.com/images/I/81CO0EkCiiL._SL1500_.jpg",
        price: 1.89,
        rating: 4.0,
        description: "Iced Green Tea",
        category: "Drinks",
    },
    {
        id: "00000033",
        name: "Sparkling Water",
        image: "https://images-na.ssl-images-amazon.com/images/I/81rp9NWcsGL._SL1500_.jpg",
        price: 4.29,
        rating: 3.9,
        description: "Pack of 12",
        category: "Drinks",
    },
    {
        id: "00000034",
        name: "Organic Green Peas",
        image: "https://images-na.ssl-images-amazon.com/images/I/81AHf9mU4oL._SL1500_.jpg",
        price: 1.67,
        rating: 2.3,
        description: "No salt added",
        category: "Vegetables",
    },
    {
        id: "00000035",
        name: "Sweet Yellow Corn",
        image: "https://images-na.ssl-images-amazon.com/images/I/81CmB8ZIzuL._SL1500_.jpg",
        price: 1.99,
        rating: 3.3,
        description: "No salt added",
        category: "Vegetables",
    },
    {
        id: "00000036",
        name: "Brussels Sprouts",
        image: "https://images-na.ssl-images-amazon.com/images/I/81xJ7fVSC2L._SL1500_.jpg",
        price: 3.49,
        rating: 4.5,
        description: "12 oz",
        category: "Vegetables",
    },
    {
        id: "00000037",
        name: "Organic Mixed Mushrooms",
        image: "https://images-na.ssl-images-amazon.com/images/I/81NKpYCDb9L._SL1500_.jpg",
        price: 4.28,
        rating: 3.2,
        description: "10 Ounce",
        category: "Vegetables",
    },
    {
        id: "00000038",
        name: "Green Beans",
        image: "https://images-na.ssl-images-amazon.com/images/I/81JVTUXGLtL._SL1500_.jpg",
        price: 3.79,
        rating: 4.4,
        description: "12 oz",
        category: "Vegetables",
    },
    {
        id: "00000039",
        name: "Organic Mixed Vegetables",
        image: "https://images-na.ssl-images-amazon.com/images/I/511V9tWssjL.jpg",
        price: 2.99,
        rating: 3.3,
        description: "16 oz",
        category: "Vegetables",
    },
    {
        id: "00000040",
        name: "Original Hummus",
        image: "https://images-na.ssl-images-amazon.com/images/I/81ThuyaPzIL._SL1500_.jpg",
        price: 3.48,
        rating: 3.5,
        description: "GMO-Free",
        category: "Canned & Packaged",
    },
    {
        id: "00000041",
        name: "Chicken Breast",
        image: "https://images-na.ssl-images-amazon.com/images/I/81vpoyRYtSL._SL1500_.jpg",
        price: 9.99,
        rating: 4.1,
        description: "Boneless Skinless",
        category: "Meat & Seafood",
    },
    {
        id: "00000042",
        name: "Organic Mango Chunks",
        image: "https://images-na.ssl-images-amazon.com/images/I/91j4HVpF9mL._SL1500_.jpg",
        price: 8.99,
        rating: 4.8,
        description: "32 oz",
        category: "Fruit",
    },
    {
        id: "00000043",
        name: "Celery Organic",
        image: "https://images-na.ssl-images-amazon.com/images/I/71coQg4V7bL._SL1500_.jpg",
        price: 2.39,
        rating: 3.8,
        description: "1 Bunch",
        category: "Vegetables",
    },
    {
        id: "00000044",
        name: "Smokehouse Bacon",
        image: "https://images-na.ssl-images-amazon.com/images/I/81WSN5pFP0L._SL1500_.jpg",
        price: 6.99,
        rating: 4.5,
        description: "12 oz",
        category: "Meat & Seafood",
    },
    {
        id: "00000045",
        name: "Florida Orange Juice",
        image: "https://images-na.ssl-images-amazon.com/images/I/814rdbgIAxL._SL1500_.jpg",
        price: 3.19,
        rating: 4.1,
        description: "Not From Concentrate",
        category: "Drinks",
    },
    {
        id: "00000046",
        name: "Organic Riced Cauliflower",
        image: "https://images-na.ssl-images-amazon.com/images/I/51bcaoeKArL.jpg",
        price: 2.39,
        rating: 3.5,
        description: "12 oz",
        category: "Vegetables",
    },
    {
        id: "00000047",
        name: "Organic Capers",
        image: "https://images-na.ssl-images-amazon.com/images/I/81M8lJhcoJL._SL1500_.jpg",
        price: 2.79,
        rating: 4.2,
        description: "2 Ounce",
        category: "Vegetables",
    },
    {
        id: "00000048",
        name: "Organic Tomato Basil",
        image: "https://images-na.ssl-images-amazon.com/images/I/81G%2BCdA8AfL._SL1500_.jpg",
        price: 2.45,
        rating: 4.7,
        description: "no sugar added",
        category: "Canned & Packaged",
    },
    {
        id: "00000049",
        name: "Oven Roasted Turkey Breast",
        image: "https://images-na.ssl-images-amazon.com/images/I/81Qi4N6N-BL._SL1500_.jpg",
        price: 6.34,
        rating: 4.6,
        description: "6 oz",
        category: "Meat & Seafood",
    },
    {
        id: "00000050",
        name: "Mom's Chicken Soup",
        image: "https://images-na.ssl-images-amazon.com/images/I/81NszJkIiBL._SL1500_.jpg",
        price: 8.79,
        rating: 4.9,
        description: "24 Ounce",
        category: "Canned & Packaged",
    },
    {
        id: "00000051",
        name: "Mild Cheddar",
        image: "https://images-na.ssl-images-amazon.com/images/I/71o0bU50d6L._SL1500_.jpg",
        price: 6.78,
        rating: 4.2,
        description: "8 Ounce",
        category: "Cheese",
    },
    {
        id: "00000052",
        name: "Chicken Noodle Soup",
        image: "https://images-na.ssl-images-amazon.com/images/I/51nIsLI91ML._SL1000_.jpg",
        price: 8.99,
        rating: 5.0,
        description: "24 Ounce",
        category: "Canned & Packaged",
    },
    {
        id: "00000053",
        name: "Aluminum Foil",
        image: "https://images-na.ssl-images-amazon.com/images/I/51nQpkuz9OL._AC_SL1000_.jpg",
        price: 9.99,
        rating: 3.5,
        description: "75 SQ FT",
        category: "Household",
    },
    {
        id: "00000054",
        name: "Paper Towels",
        image: "https://images-na.ssl-images-amazon.com/images/I/81MPjbfxSyL._SL1500_.jpg",
        price: 2.89,
        rating: 4.3,
        description: "100% Recycled",
        category: "Household",
    },
    {
        id: "00000055",
        name: "Organic Black Beans",
        image: "https://images-na.ssl-images-amazon.com/images/I/81ySDQkEBPL._SL1500_.jpg",
        price: 1.39,
        rating: 4.6,
        description: "15 Ounce",
        category: "Canned & Packaged",
    },
    {
        id: "00000056",
        name: "Freezer Bags",
        image: "https://images-na.ssl-images-amazon.com/images/I/81mPfZNE39L._AC_SL1500_.jpg",
        price: 3.56,
        rating: 4.2,
        description: "Double Zipper",
        category: "Household",
    },
    {
        id: "00000057",
        name: "Grated Parmesan Cheese",
        image: "https://images-na.ssl-images-amazon.com/images/I/81HXUmsXk%2BL._SL1500_.jpg",
        price: 4.99,
        rating: 4.9,
        description: "5 Ounce",
        category: "Cheese",
    },
    {
        id: "00000058",
        name: "Organic Garbanzo Beans",
        image: "https://images-na.ssl-images-amazon.com/images/I/818aBRiMh5L._SL1500_.jpg",
        price: 1.49,
        rating: 2.5,
        description: "15.5 Ounce",
        category: "Canned & Packaged",
    },
    {
        id: "00000059",
        name: "Red Onion",
        image: "https://images-na.ssl-images-amazon.com/images/I/710UWZni6OL._SL1500_.jpg",
        price: 1.79,
        rating: 3.3,
        description: "Organic",
        category: "Vegetables",
    },
    {
        id: "00000060",
        name: "Mozzarella",
        image: "https://images-na.ssl-images-amazon.com/images/I/71i%2BNUAPQLL._SL1500_.jpg",
        price: 9.99,
        rating: 3.5,
        description: "16 Ounce",
        category: "Cheese",
    },
    {
        id: "00000061",
        name: "Berry Blackberries",
        image: "https://images-na.ssl-images-amazon.com/images/I/71xhUK%2B4x5L._SL1383_.jpg",
        price: 5.19,
        rating: 3.9,
        description: "6 Ounce",
        category: "Fruit",
    },
    {
        id: "00000062",
        name: "Zucchini Squash",
        image: "https://images-na.ssl-images-amazon.com/images/I/71PgqGZENTL._SL1500_.jpg",
        price: 2.99,
        rating: 4.6,
        description: "Organic",
        category: "Vegetables",
    },
    {
        id: "00000063",
        name: "Pumpkin Puree",
        image: "https://images-na.ssl-images-amazon.com/images/I/91raDkFurSL._SL1500_.jpg",
        price: 1.69,
        rating: 5.0,
        description: "15 oz",
        category: "Canned & Packaged",
    },
    {
        id: "00000064",
        name: "Tall Kitchen Bags",
        image: "https://images-na.ssl-images-amazon.com/images/I/81IjRLxN76L._AC_SL1500_.jpg",
        price: 6.98,
        rating: 4.1,
        description: "38 Count",
        category: "Household",
    },
    {
        id: "00000065",
        name: "Stella Artois 6 Pack Beer",
        image: "https://images-na.ssl-images-amazon.com/images/I/81VQQy1oV6L._AC_SL1500_.jpg",
        price: 10.99,
        rating: 4.9,
        description: "11.2 fl oz bottles",
        category: "Drinks",
    },
    {
        id: "00000066",
        name: "Organic Heavy Cream",
        image: "https://images-na.ssl-images-amazon.com/images/I/81J9iaRIzKL._SL1500_.jpg",
        price: 4.39,
        rating: 3.7,
        description: "16 fl oz",
        category: "Dairy",
    },
    {
        id: "00000067",
        name: "Organic Egg",
        image: "https://images-na.ssl-images-amazon.com/images/I/81P43am0S0L._SL1500_.jpg",
        price: 8.99,
        rating: 4.8,
        description: "18 Count",
        category: "Egg",
    },
    {
        id: "00000068",
        name: "Pure Irish Butter",
        image: "https://images-na.ssl-images-amazon.com/images/I/81BkFw7uWKL._SL1500_.jpg",
        price: 6.79,
        rating: 5.0,
        description: "8 oz",
        category: "Vegetables",
    },
    {
        id: "00000069",
        name: "Natural By Nature Whipped Cream",
        image: "https://images-na.ssl-images-amazon.com/images/I/71XgmU7LWoL._SL1500_.jpg",
        price: 5.99,
        rating: 4.7,
        description: "7 oz",
        category: "Dairy",
    },
    {
        id: "00000070",
        name: "Daisy Regular Sour Cream",
        image: "https://images-na.ssl-images-amazon.com/images/I/71xcAOJixoL._SL1500_.jpg",
        price: 1.49,
        rating: 3.9,
        description: "8 oz",
        category: "Dairy",
    },
    {
        id: "00000071",
        name: "Italian Bread",
        image: "https://images-na.ssl-images-amazon.com/images/I/812FZA26UOL._SL1500_.jpg",
        price: 5.29,
        rating: 4.3,
        description: "18 Ounce",
        category: "Bread",
    },
    {
        id: "00000072",
        name: "Whole Pumpkin Pie",
        image: "https://images-na.ssl-images-amazon.com/images/I/61x3Y3L%2BgaL._SL1000_.jpg",
        price: 13.99,
        rating: 2.8,
        description: "30 Ounce",
        category: "Canned & Packaged",
    },
    {
        id: "00000073",
        name: "Cookie Chocolate",
        image: "https://images-na.ssl-images-amazon.com/images/I/81oueIRNkyL._SL1500_.jpg",
        price: 5.99,
        rating: 4.0,
        description: "10 Count",
        category: "Canned & Packaged",
    },
    {
        id: "00000074",
        name: "Cake Tiramisu",
        image: "https://images-na.ssl-images-amazon.com/images/I/81axm-YtT7L._SL1500_.jpg",
        price: 32.99,
        rating: 4.3,
        description: "85 Ounce",
        category: "Canned & Packaged",
    },
    {
        id: "00000075",
        name: "Cooked White Shrimp",
        image: "https://images-na.ssl-images-amazon.com/images/I/61p3znOZEiL._SL1000_.jpg",
        price: 20.99,
        rating: 3.9,
        description: "20 Count",
        category: "Meat & Seafood",
    },
    {
        id: "00000076",
        name: "Chicken Pate",
        image: "https://images-na.ssl-images-amazon.com/images/I/8145aXf4ScL._SL1500_.jpg",
        price: 1.29,
        rating: 4.1,
        description: "Grain Free",
        category: "Meat & Seafood",
    },
    {
        id: "00000077",
        name: "Chicken, Turkey & Salmon Feast",
        image: "https://images-na.ssl-images-amazon.com/images/I/81AGKphS3rL._SL1500_.jpg",
        price: 2.29,
        rating: 4.3,
        description: "13.2",
        category: "Meat & Seafood",
    },
    {
        id: "00000078",
        name: "Hand Sanitizer Wipes",
        image: "https://images-na.ssl-images-amazon.com/images/I/51dZ8M4shqL._SL1000_.jpg",
        price: 2.19,
        rating: 3.5,
        description: "Lavender",
        category: "Household",
    },
    {
        id: "00000079",
        name: "Coconut Oil",
        image: "https://images-na.ssl-images-amazon.com/images/I/61vIwm%2Bm6xL._SL1000_.jpg",
        price: 8.59,
        rating: 3.8,
        description: "15 Oz",
        category: "Canned & Packaged",
    },
    {
        id: "00000080",
        name: "Mild Guacamole",
        image: "https://images-na.ssl-images-amazon.com/images/I/61-gjxT-AmL._SL1000_.jpg",
        price: 7.29,
        rating: 3.5,
        description: "Fresh",
        category: "Canned & Packaged",
    },
    {
        id: "00000081",
        name: "White Pizza Dough",
        image: "https://images-na.ssl-images-amazon.com/images/I/41Br05gcvCL._SL1024_.jpg",
        price: 3.39,
        rating: 4.5,
        description: "22 Ounce",
        category: "Canned & Packaged",
    },
    {
        id: "00000082",
        name: "Butternut Squash",
        image: "https://images-na.ssl-images-amazon.com/images/I/81G-VNvdcoL._SL1500_.jpg",
        price: 3.19,
        rating: 4.6,
        description: "16 Ounce",
        category: "Canned & Packaged",
    },
    {
        id: "00000083",
        name: "Grapefruit",
        image: "https://images-na.ssl-images-amazon.com/images/I/71opx019wyL._SL1500_.jpg",
        price: 1.48,
        rating: 4.2,
        description: "Organic",
        category: "Fruits",
    },
    {
        id:"00000084",
        name: "Honeycrisp Apple",
        image: "https://images-na.ssl-images-amazon.com/images/I/71cz19QjhAL._SL1500_.jpg",
        price: 3.29,
        rating: 4.5,
        description: "Organic",
        category: "Vegetables",
    },
    {
        id: "00000085",
        name: "Banana Nini Baby",
        image: "https://images-na.ssl-images-amazon.com/images/I/51hktYuUoIL._SL1024_.jpg",
        price: 2.39,
        rating: 5.0,
        description: "Organic",
        category: "Fruit",
    },
    {
        id: "00000086",
        name: "Pineapple",
        image: "https://images-na.ssl-images-amazon.com/images/I/71NIN-aJLkL._SL1500_.jpg",
        price: 3.29,
        rating: 4.3,
        description: "Organic",
        category: "Fruit",
    },
    {
        id: "00000087",
        name: "Golden Kiwi",
        image: "https://images-na.ssl-images-amazon.com/images/I/81shlkkHlrL._SL1500_.jpg",
        price: 5.59,
        rating: 4.6,
        description: "16 Ounce",
        category: "Fruit",
    },
    {
        id: "00000088",
        name: "Pomegranate",
        image: "https://images-na.ssl-images-amazon.com/images/I/81VTOcrqGHL._SL1500_.jpg",
        price: 4.29,
        rating: 3.5,
        description: "Organic",
        category: "Vegetables",
    },
    {
        id: "00000089",
        name: "Mango",
        image: "https://images-na.ssl-images-amazon.com/images/I/81MSCpQpFWL._SL1500_.jpg",
        price: 2.74,
        rating: 2.1,
        description: "Organic",
        category: "Fruit",
    },
    {
        id: "00000090",
        name: "Red Grape",
        image: "https://images-na.ssl-images-amazon.com/images/I/71e64jCSuGL._SL1500_.jpg",
        price: 3.69,
        rating: 4.5,
        description: "Organic",
        category: "Fruit",
    },
    {
        id: "00000091",
        name: "Melon Cantaloupe",
        image: "https://images-na.ssl-images-amazon.com/images/I/81sY9fWfIRL._SL1500_.jpg",
        price: 4.39,
        rating: 2.5,
        description: "Organic",
        category: "Fruit",
    },
    {
        id: "00000092",
        name: "Watermelon",
        image: "https://images-na.ssl-images-amazon.com/images/I/81FSROXr2LL._SL1500_.jpg",
        price: 7.89,
        rating: 3.5,
        description: "Organic",
        category: "Fruit",
    },
    {
        id: "00000093",
        name: "Kale",
        image: "https://images-na.ssl-images-amazon.com/images/I/51rTC36HypL.jpg",
        price: 1.89,
        rating: 4.1,
        description: "1 Bunch",
        category: "Vegetables",
    },
    {
        id: "00000094",
        name: "Iceberg Lettuce",
        image: "https://images-na.ssl-images-amazon.com/images/I/71z9tMnKSCL._SL1330_.jpg",
        price: 1.73,
        rating: 2.8,
        description: "Organic",
        category: "Vegetables",
    },
    {
        id: "00000095",
        name: "Red Potato",
        image: "https://images-na.ssl-images-amazon.com/images/I/81a8s3LqDpL._SL1500_.jpg",
        price: 1.59,
        rating: 4.3,
        description: "Organic",
        category: "Vegetables",
    },
    {
        id: "00000096",
        name: "Yellow Potato",
        image: "https://images-na.ssl-images-amazon.com/images/I/517UHE15lGL.jpg",
        price: 1.89,
        rating: 3.7,
        description: "Organic",
        category: "Vegetables",
    },
    {
        id: "00000097",
        name: "Eggplant",
        image: "https://images-na.ssl-images-amazon.com/images/I/71oT8iD05-L._SL1500_.jpg",
        price: 2.74,
        rating: 4.2,
        description: "Organic",
        category: "Vegetables",
    },
    {
        id: "00000099",
        name: "Garlic",
        image: "https://images-na.ssl-images-amazon.com/images/I/71KpWVcGo5L._SL1500_.jpg",
        price: 4.25,
        rating: 4.9,
        description: "Organic",
        category: "Vegetables",
    },
    {
        id: "00000100",
        name: "Green Asparagus",
        image: "https://images-na.ssl-images-amazon.com/images/I/71qYLp6aluL._SL1500_.jpg",
        price: 6.99,
        rating: 4.2,
        description: "Organic",
        category: "Vegetables",
    },
    {
        id: "00000101",
        name: "Roma Tomato",
        image: "https://images-na.ssl-images-amazon.com/images/I/71sm7jOErBL._SL1500_.jpg",
        price: 2.13,
        rating: 4.8,
        description: "Organic",
        category: "Vegetables",
    },
    {
        id: "00000102",
        name: "Cabbage",
        image: "https://images-na.ssl-images-amazon.com/images/I/71IoNP7O8eL._SL1500_.jpg",
        price: 1.29,
        rating: 4.1,
        description: "Organic",
        category: "Vegetables",
    },
    {
        id: "00000103",
        name: "Organic Strawberry Fruit Spread",
        image: "https://images-na.ssl-images-amazon.com/images/I/81zWLysSnhL._SL1500_.jpg",
        price: 4.43,
        rating: 3.8,
        description: "17 Ounce",
        category: "Fruit",
    },
    {
        id: "00000104",
        name: "Justin's Peanut Butter",
        image: "https://images-na.ssl-images-amazon.com/images/I/619JjERx6mL._SL1500_.jpg",
        price: 5.29,
        rating: 5.0,
        description: "16 Oz",
        category: "Fruit",
        category: "meat",
    },
];
export default products;